jobs:
  ci:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./verify/workflow

name: Run

on:
  schedule:
    - cron: "30 */6 * * *"
